paths = [
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/source_code_simplifier.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/add_two_blank_lines_before_first_class_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/add_two_blank_lines_between_classes_and_defs_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/convert_double_quotes_to_single_quotes_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/convert_is_to_equality_when_comparing_with_constant_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/convert_to_four_spaces_indentation_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_blank_line_at_end_of_file_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_blank_line_contains_whitespace_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_comparison_to_none_should_be_cond_is_none_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_comparison_to_true_should_be_if_cond_is_true_or_if_cond_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_do_not_compare_types_use_isinstance_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_float_to_full_representation_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_import_not_at_top_of_file_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_invalid_escape_sequence_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_lines_after_def_decorator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_missing_whitespace_after_comma_semicolon_or_colon_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_missing_whitespace_after_keyword_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_missing_whitespace_around_arithmetic_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_missing_whitespace_around_bitwise_or_shift_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_missing_whitespace_around_modulo_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_missing_whitespace_around_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_multiple_imports_in_one_line_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_multiple_spaces_after_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_multiple_spaces_before_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_multiple_statements_on_one_line_colon_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_multiple_statements_on_one_line_def_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_multiple_statements_on_one_line_semicolon_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_one_blank_line_between_methods_of_class_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_statement_ends_with_semicolon_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_tab_after_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_tab_around_keyword_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_tab_before_operator_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_test_for_membership_should_be_not_in_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_test_for_object_identity_should_be_is_not_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_trailing_whitespace_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_tuple_parenthesis_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_two_blank_lines_after_imports_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_two_blank_lines_before_if_main_name_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_two_blank_lines_between_defs_and_classes_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_whitespace_around_comma_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_whitespace_around_keyword_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_whitespace_around_keyword_equals_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_whitespace_before_colon_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/fix_whitespaces_around_parenthesis_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_async_await.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_classes_that_contain_non_defs.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_empty_def.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_globals.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_import_from_logging.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_import_from_star.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_import_from_with_non_module_parent.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_import_logging.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_import_submodule.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_import_with_non_module_parent.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_lambda_assignments.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_local_variable_named_builtin.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_nested_classes.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_nested_defs.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_non_capitalized_class_names.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_printf_strings.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_relative_imports.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_single_letter_class_names.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_single_letter_def_names.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_single_letter_variable_names.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_statements_outside_of_blocks.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_try_except.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_unsorted_def_arguments.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/forbid_uppercase_in_assignment_names.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/merge_multiple_import_from_with_same_module_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/move_classes_before_defs_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_breakpoints_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_comments_inline_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_comments_whole_line_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_continuation_character_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_docstrings_double_quoted_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_docstrings_double_quoted_multi_line_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_docstrings_single_quoted_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_docstrings_single_quoted_multi_line_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_duplicate_import_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_duplicate_import_from_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_empty_for_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_empty_if_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_extra_parenthesis_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_non_call_expressions_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_object_inheritance_from_class_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_prints_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_trailing_comma_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_type_hints_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_unneeded_parenthesis_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_unused_import_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/remove_unused_import_froms_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/retain_double_quotes_when_contain_single_quote_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/sort_classes_in_module_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/sort_defs_in_class_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/sort_defs_in_module_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/sort_imports_bad.py",
	"https://raw.githubusercontent.com/pbizopoulos/source-code-simplifier/main/tests/sort_imports_from_bad.py",
	]
